2022-03-14 23:03:09,776 ERROR: Exception on /auth/login [GET] [in /home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kenneth/myrenamer/app/auth/routes.py", line 26, in login
    return render_template('login.html', title=_('Sign In'), form=form)
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2022-03-14 23:05:33,579 INFO: My Renamer Startup [in /home/kenneth/myrenamer/app/__init__.py:74]
